# Generated by Django 5.1.8 on 2025-07-07 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_strength', models.FloatField(default=0.35)),
                ('default_aspect_ratio', models.CharField(default='1:1', max_length=10)),
                ('compatible_themes', models.JSONField(default=list, help_text='List of wedding themes this preset works well with')),
                ('compatible_spaces', models.JSONField(default=list, help_text='List of space types this preset works well with')),
                ('recommended_for_guest_counts', models.JSONField(default=list, help_text='Guest count categories this works well for')),
                ('recommended_for_budgets', models.JSONField(default=list, help_text='Budget levels this works well for')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='cfg_scale',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='steps',
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='budget_level',
            field=models.CharField(blank=True, help_text='Budget level', max_length=20),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='color_scheme',
            field=models.CharField(blank=True, help_text='Color scheme', max_length=30),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='custom_colors',
            field=models.CharField(blank=True, help_text='Custom colors', max_length=200),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='guest_count',
            field=models.CharField(blank=True, help_text='Guest count category', max_length=20),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='season',
            field=models.CharField(blank=True, help_text='Wedding season', max_length=20),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='time_of_day',
            field=models.CharField(blank=True, help_text='Time of day', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='aspect_ratio',
            field=models.CharField(default='1:1', help_text='Aspect ratio for output image', max_length=10),
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this template', max_length=100)),
                ('template_type', models.CharField(choices=[('theme', 'Wedding Theme Template'), ('space', 'Space Type Template'), ('guest_modifier', 'Guest Count Modifier'), ('budget_modifier', 'Budget Level Modifier'), ('season_modifier', 'Season Modifier'), ('time_modifier', 'Time of Day Modifier'), ('color_modifier', 'Color Scheme Modifier'), ('base_prompt', 'Base Prompt Template'), ('negative_prompt', 'Negative Prompt Template')], max_length=20)),
                ('identifier', models.CharField(help_text="Unique identifier (e.g., 'rustic', 'budget', 'spring')", max_length=50)),
                ('prompt_text', models.TextField(help_text='The actual prompt text. Use {variables} for dynamic content.')),
                ('description', models.TextField(blank=True, help_text='Description of what this template does')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority templates are used first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_strength', models.FloatField(default=0.35, help_text='Recommended transformation strength for this template')),
                ('recommended_aspect_ratio', models.CharField(default='1:1', help_text='Recommended aspect ratio', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('template_type', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='ProcessingJobEnhanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_count', models.CharField(blank=True, help_text='intimate, medium, large, grand', max_length=20)),
                ('budget_level', models.CharField(blank=True, help_text='budget, moderate, luxury, ultra_luxury', max_length=20)),
                ('season', models.CharField(blank=True, help_text='spring, summer, fall, winter', max_length=20)),
                ('time_of_day', models.CharField(blank=True, help_text='morning, afternoon, evening, night', max_length=20)),
                ('color_scheme', models.CharField(blank=True, help_text='Color scheme choice', max_length=30)),
                ('custom_colors', models.CharField(blank=True, help_text='Custom color specification', max_length=200)),
                ('generate_variations', models.BooleanField(default=False)),
                ('final_compiled_prompt', models.TextField(blank=True, help_text='The final prompt sent to AI')),
                ('base_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_data', to='image_processing.imageprocessingjob')),
                ('used_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_processing.generationpreset')),
                ('used_prompt_templates', models.ManyToManyField(blank=True, to='image_processing.prompttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PromptVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prompt_text', models.TextField(help_text='Alternative prompt text')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate based on user ratings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='image_processing.prompttemplate')),
            ],
            options={
                'ordering': ['-success_rate', '-usage_count'],
            },
        ),
    ]
