# Generated by Django 5.1.8 on 2025-07-08 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_auto_20250707_1831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'processed_image')},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='processed_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='image_processing.processedimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(blank=True, choices=[('wedding_ceremony', 'Wedding Ceremony'), ('reception_area', 'Reception Area'), ('dance_floor', 'Dance Floor'), ('dinner_party', 'Dinner Party'), ('cocktail_hour', 'Cocktail Hour'), ('bridal_suite', 'Bridal Suite'), ('photo_backdrop', 'Photo Backdrop'), ('lounge_area', 'Lounge Area')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user_image',
        ),
    ]
