# Generated by Django 5.1.8 on 2025-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(blank=True, choices=[('wedding_ceremony', 'Wedding Ceremony'), ('reception_area', 'Reception Area'), ('dance_floor', 'Dance Floor'), ('dinner_party', 'Dinner Party'), ('cocktail_hour', 'Cocktail Hour'), ('bridal_suite', 'Bridal Suite'), ('photo_backdrop', 'Photo Backdrop'), ('lounge_area', 'Lounge Area'), ('ballroom', 'Grand Ballroom'), ('barn', 'Rustic Barn'), ('garden', 'Garden/Outdoor'), ('rooftop', 'Rooftop Terrace'), ('beach', 'Beach/Seaside'), ('warehouse', 'Urban Warehouse'), ('mansion', 'Elegant Mansion'), ('vineyard', 'Wine Country Vineyard')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='wedding_theme',
            field=models.CharField(blank=True, choices=[('rustic', 'Rustic Farmhouse'), ('modern', 'Modern Contemporary'), ('vintage', 'Vintage Romance'), ('bohemian', 'Bohemian Chic'), ('classic', 'Classic Traditional'), ('garden', 'Garden Natural'), ('beach', 'Beach Coastal'), ('industrial', 'Industrial Urban'), ('glamorous', 'Glamorous Luxury'), ('tropical', 'Tropical Paradise'), ('fairy_tale', 'Fairy Tale Enchanted'), ('cultural_fusion', 'Cultural Fusion')], max_length=20, null=True),
        ),
    ]
