# Generated by Django 5.1.8 on 2025-07-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0005_alter_imageprocessingjob_space_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(blank=True, choices=[('wedding_ceremony', 'Wedding Ceremony'), ('reception_area', 'Reception Area'), ('dance_floor', 'Dance Floor'), ('dinner_party', 'Dinner Party'), ('cocktail_hour', 'Cocktail Hour'), ('bridal_suite', 'Bridal Suite'), ('photo_backdrop', 'Photo Backdrop'), ('lounge_area', 'Lounge Area')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='wedding_theme',
            field=models.CharField(blank=True, choices=[('japanese_zen', 'Japanese Zen'), ('chinese_dynasty', 'Chinese Dynasty'), ('indian_palace', 'Indian Palace'), ('korean_hanbok', 'Korean Hanbok'), ('thai_temple', 'Thai Temple'), ('scottish_highland', 'Scottish Highland'), ('french_chateau', 'French Château'), ('greek_island', 'Greek Island'), ('italian_villa', 'Italian Villa'), ('english_garden', 'English Garden'), ('mexican_fiesta', 'Mexican Fiesta'), ('spanish_hacienda', 'Spanish Hacienda'), ('brazilian_carnival', 'Brazilian Carnival'), ('argentine_tango', 'Argentine Tango'), ('moroccan_nights', 'Moroccan Nights'), ('arabian_desert', 'Arabian Desert'), ('african_safari', 'African Safari'), ('egyptian_royal', 'Egyptian Royal'), ('winter_wonderland', 'Winter Wonderland'), ('spring_awakening', 'Spring Awakening'), ('summer_solstice', 'Summer Solstice'), ('autumn_harvest', 'Autumn Harvest'), ('forest_enchanted', 'Enchanted Forest'), ('desert_bloom', 'Desert Bloom'), ('ocean_waves', 'Ocean Waves'), ('mountain_vista', 'Mountain Vista'), ('tropical_paradise', 'Tropical Paradise'), ('metropolitan_chic', 'Metropolitan Chic'), ('brooklyn_loft', 'Brooklyn Loft'), ('rooftop_garden', 'Rooftop Garden'), ('art_deco_glam', 'Art Deco Glam'), ('scandinavian_simple', 'Scandinavian Simple'), ('modern_monochrome', 'Modern Monochrome'), ('concrete_jungle', 'Concrete Jungle'), ('glass_house', 'Glass House'), ('1950s_diner', '1950s Diner'), ('1960s_mod', '1960s Mod'), ('1970s_disco', '1970s Disco'), ('1980s_neon', '1980s Neon'), ('1990s_grunge', '1990s Grunge'), ('victorian_romance', 'Victorian Romance'), ('art_nouveau', 'Art Nouveau'), ('great_gatsby', 'Great Gatsby'), ('enchanted_forest_fairy', 'Enchanted Forest Fairy'), ('princess_castle', 'Princess Castle'), ('mermaid_lagoon', 'Mermaid Lagoon'), ('dragon_castle', 'Dragon & Castle'), ('unicorn_dreams', 'Unicorn Dreams'), ('hollywood_glam', 'Hollywood Glam'), ('broadway_musical', 'Broadway Musical'), ('vintage_circus', 'Vintage Circus'), ('comic_book', 'Comic Book'), ('christmas_magic', 'Christmas Magic'), ('halloween_gothic', 'Halloween Gothic'), ('valentine_romance', 'Valentine Romance'), ('new_year_eve', "New Year's Eve"), ('fourth_july', 'Fourth of July'), ('dia_muertos', 'Día de los Muertos'), ('chinese_new_year', 'Chinese New Year'), ('oktoberfest', 'Oktoberfest'), ('mardi_gras', 'Mardi Gras'), ('book_lovers', 'Book Lovers'), ('music_festival', 'Music Festival'), ('travel_adventure', 'Travel Adventure'), ('wine_country', 'Wine Country'), ('coffee_house', 'Coffee House'), ('neon_cyberpunk', 'Neon Cyberpunk'), ('steampunk_victorian', 'Steampunk Victorian'), ('space_galaxy', 'Space Galaxy'), ('under_the_sea', 'Under the Sea'), ('secret_garden', 'Secret Garden'), ('rustic', 'Rustic Barn'), ('modern', 'Modern Elegant'), ('vintage', 'Vintage Romance'), ('bohemian', 'Bohemian Chic'), ('classic', 'Classic Traditional'), ('garden', 'Garden Party'), ('beach', 'Beach Paradise'), ('industrial', 'Industrial Chic')], max_length=50, null=True),
        ),
    ]
