# Generated by Django 5.1.8 on 2025-07-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0006_alter_imageprocessingjob_space_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationpreset',
            name='default_aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='recommended_aspect_ratio',
        ),
        migrations.AddField(
            model_name='generationpreset',
            name='default_cfg_scale',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='generationpreset',
            name='default_steps',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='cfg_scale',
            field=models.FloatField(default=7.0, help_text='How strictly the diffusion process adheres to the prompt text (1.0-20.0)'),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='steps',
            field=models.IntegerField(default=50, help_text='Number of diffusion steps to run (10-150)'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='recommended_cfg_scale',
            field=models.FloatField(default=7.0, help_text='Recommended CFG scale for this template'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='recommended_steps',
            field=models.IntegerField(default=50, help_text='Recommended steps for this template'),
        ),
        migrations.AlterField(
            model_name='generationpreset',
            name='default_strength',
            field=models.FloatField(default=0.4),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='aspect_ratio',
            field=models.CharField(default='1:1', help_text='Aspect ratio (not used in image-to-image mode - maintains original dimensions)', max_length=10),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='strength',
            field=models.FloatField(default=0.4, help_text='How much the input image influences the output (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='recommended_strength',
            field=models.FloatField(default=0.4, help_text='Recommended transformation strength for this template'),
        ),
    ]
