# Generated by Django 5.1.8 on 2025-07-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0007_remove_generationpreset_default_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(blank=True, choices=[('wedding_ceremony', 'Wedding Ceremony'), ('dance_floor', 'Dance Floor'), ('dining_area', 'Dining Area'), ('cocktail_hour', 'Cocktail Hour'), ('lounge_area', 'Lounge Area')], max_length=20, null=True),
        ),
    ]
