# Generated by Django 5.1.8 on 2025-07-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0008_alter_imageprocessingjob_space_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedimage',
            name='is_saved',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='saved_at',
        ),
    ]
