# Generated by Django 5.1.8 on 2025-08-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0009_remove_processedimage_is_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='budget_level',
            field=models.CharField(blank=True, help_text='budget, moderate, luxury', max_length=20),
        ),
    ]
