# Generated by Django 5.1.8 on 2025-08-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0010_alter_processingjobenhanced_budget_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='budget_level',
            field=models.CharField(blank=True, help_text='budget, moderate, luxury', max_length=20, null=True),
        ),
    ]
