# Generated by Django 5.1.8 on 2025-08-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0011_alter_processingjobenhanced_budget_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingjob',
            name='religion_culture',
            field=models.CharField(blank=True, help_text='Religion or cultural background for appropriate elements', max_length=30),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='user_negative_prompt',
            field=models.TextField(blank=True, help_text='User-specified things to avoid or remove from the transformation', null=True),
        ),
        migrations.AddField(
            model_name='processingjobenhanced',
            name='religion_culture',
            field=models.CharField(blank=True, help_text='Religion or cultural background', max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='negative_prompt',
            field=models.TextField(blank=True, help_text='Final negative prompt combining system and user preferences', null=True),
        ),
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='budget_level',
            field=models.CharField(blank=True, default='', help_text='budget, moderate, luxury', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='identifier',
            field=models.CharField(help_text="Unique identifier (e.g., 'rustic', 'budget', 'spring', 'hindu')", max_length=50),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='template_type',
            field=models.CharField(choices=[('theme', 'Wedding Theme Template'), ('space', 'Space Type Template'), ('guest_modifier', 'Guest Count Modifier'), ('budget_modifier', 'Budget Level Modifier'), ('season_modifier', 'Season Modifier'), ('time_modifier', 'Time of Day Modifier'), ('color_modifier', 'Color Scheme Modifier'), ('religion_modifier', 'Religion/Culture Modifier'), ('base_prompt', 'Base Prompt Template'), ('negative_prompt', 'Negative Prompt Template')], max_length=20),
        ),
    ]
