# Generated by Django 5.1.8 on 2025-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0012_imageprocessingjob_religion_culture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationpreset',
            name='recommended_for_budgets',
        ),
        migrations.RemoveField(
            model_name='generationpreset',
            name='recommended_for_guest_counts',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='custom_colors',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='religion_culture',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='user_negative_prompt',
        ),
        migrations.RemoveField(
            model_name='processingjobenhanced',
            name='custom_colors',
        ),
        migrations.RemoveField(
            model_name='processingjobenhanced',
            name='religion_culture',
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='avoid',
            field=models.TextField(blank=True, help_text='Things to avoid in the transformation', null=True),
        ),
        migrations.AlterField(
            model_name='generationpreset',
            name='compatible_spaces',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='generationpreset',
            name='compatible_themes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='generationpreset',
            name='default_cfg_scale',
            field=models.FloatField(default=7.5),
        ),
        migrations.AlterField(
            model_name='generationpreset',
            name='default_steps',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='generationpreset',
            name='default_strength',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='generationpreset',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='cfg_scale',
            field=models.FloatField(default=7.5, help_text='CFG scale for SD3.5 Large (1.0-20.0)'),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='negative_prompt',
            field=models.TextField(blank=True, help_text='Final negative prompt', null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='seed',
            field=models.BigIntegerField(blank=True, help_text='Random seed for generation', null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(blank=True, choices=[('wedding_ceremony', 'Wedding Ceremony'), ('dance_floor', 'Dance Floor'), ('dining_area', 'Reception Dining'), ('cocktail_hour', 'Cocktail Hour'), ('lounge_area', 'Lounge Area')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='steps',
            field=models.IntegerField(default=40, help_text='Number of steps for SD3.5 Large (10-100)'),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='strength',
            field=models.FloatField(default=0.9, help_text='Transformation strength - high for major changes (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='wedding_theme',
            field=models.CharField(blank=True, choices=[('rustic', 'Rustic Farmhouse'), ('modern', 'Modern Contemporary'), ('vintage', 'Vintage Romance'), ('bohemian', 'Bohemian Chic'), ('classic', 'Classic Traditional'), ('garden', 'Garden Natural'), ('beach', 'Beach Coastal'), ('industrial', 'Industrial Urban'), ('glamorous', 'Glamorous Luxury'), ('tropical', 'Tropical Paradise'), ('fairy_tale', 'Fairy Tale Enchanted'), ('cultural_fusion', 'Cultural Fusion'), ('japanese_zen', 'Japanese Zen'), ('chinese_dynasty', 'Chinese Dynasty'), ('indian_palace', 'Indian Palace'), ('korean_hanbok', 'Korean Hanbok'), ('thai_temple', 'Thai Temple'), ('scottish_highland', 'Scottish Highland'), ('french_chateau', 'French Château'), ('greek_island', 'Greek Island'), ('italian_villa', 'Italian Villa'), ('english_garden', 'English Garden'), ('mexican_fiesta', 'Mexican Fiesta'), ('spanish_hacienda', 'Spanish Hacienda'), ('brazilian_carnival', 'Brazilian Carnival'), ('argentine_tango', 'Argentine Tango'), ('moroccan_nights', 'Moroccan Nights'), ('arabian_desert', 'Arabian Desert'), ('african_safari', 'African Safari'), ('egyptian_royal', 'Egyptian Royal'), ('winter_wonderland', 'Winter Wonderland'), ('spring_awakening', 'Spring Awakening'), ('summer_solstice', 'Summer Solstice'), ('autumn_harvest', 'Autumn Harvest'), ('forest_enchanted', 'Enchanted Forest'), ('desert_bloom', 'Desert Bloom'), ('ocean_waves', 'Ocean Waves'), ('mountain_vista', 'Mountain Vista'), ('metropolitan_chic', 'Metropolitan Chic'), ('brooklyn_loft', 'Brooklyn Loft'), ('rooftop_garden', 'Rooftop Garden'), ('art_deco_glam', 'Art Deco Glam'), ('scandinavian_simple', 'Scandinavian Simple'), ('modern_monochrome', 'Modern Monochrome'), ('concrete_jungle', 'Concrete Jungle'), ('glass_house', 'Glass House'), ('1950s_diner', '1950s Diner'), ('1960s_mod', '1960s Mod'), ('1970s_disco', '1970s Disco'), ('1980s_neon', '1980s Neon'), ('1990s_grunge', '1990s Grunge'), ('victorian_romance', 'Victorian Romance'), ('art_nouveau', 'Art Nouveau'), ('great_gatsby', 'Great Gatsby')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='budget_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='color_scheme',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='final_compiled_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='guest_count',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='season',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjobenhanced',
            name='time_of_day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='identifier',
            field=models.CharField(help_text='Unique identifier', max_length=50),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='prompt_text',
            field=models.TextField(help_text='The actual prompt text'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='recommended_cfg_scale',
            field=models.FloatField(default=7.5),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='recommended_steps',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='recommended_strength',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='template_type',
            field=models.CharField(choices=[('theme', 'Wedding Theme Template'), ('space', 'Space Type Template'), ('guest_modifier', 'Guest Count Modifier'), ('budget_modifier', 'Budget Level Modifier'), ('season_modifier', 'Season Modifier'), ('time_modifier', 'Time of Day Modifier'), ('color_modifier', 'Color Scheme Modifier'), ('base_prompt', 'Base Prompt Template'), ('negative_prompt', 'Negative Prompt Template')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PromptVariation',
        ),
    ]
