# Generated by Django 5.1.8 on 2025-08-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0013_remove_generationpreset_recommended_for_budgets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingjob',
            name='lighting_mood',
            field=models.CharField(blank=True, help_text='Desired lighting atmosphere', max_length=20),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='special_features',
            field=models.TextField(blank=True, help_text='Special architectural features of the space', null=True),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='style_intensity',
            field=models.CharField(blank=True, help_text='Transformation intensity level', max_length=20),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='venue_context',
            field=models.CharField(blank=True, help_text='Indoor/outdoor context', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(blank=True, choices=[('wedding_ceremony', 'Wedding Ceremony'), ('dance_floor', 'Dance Floor / Party Area'), ('dining_area', 'Reception Dining'), ('cocktail_hour', 'Cocktail Reception'), ('lounge_area', 'Lounge / Seating Area'), ('bridal_suite', 'Bridal Suite / Getting Ready'), ('entrance_area', 'Entrance / Welcome Area'), ('outdoor_patio', 'Outdoor Patio / Terrace'), ('garden_space', 'Garden / Courtyard'), ('ballroom', 'Grand Ballroom')], max_length=20, null=True),
        ),
    ]
