# Generated by Django 5.1.8 on 2025-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0014_imageprocessingjob_lighting_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingjobenhanced',
            name='used_preset',
        ),
        migrations.RemoveField(
            model_name='processingjobenhanced',
            name='base_job',
        ),
        migrations.RemoveField(
            model_name='processingjobenhanced',
            name='used_prompt_templates',
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='budget_level',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='venue_context',
        ),
        migrations.AddField(
            model_name='userimage',
            name='venue_description',
            field=models.TextField(blank=True, help_text='Description of the venue space'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='venue_name',
            field=models.CharField(blank=True, help_text='Name of the venue', max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Personal notes about this design', null=True),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='avoid',
            field=models.TextField(blank=True, help_text='Elements to avoid in the transformation', null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='cfg_scale',
            field=models.FloatField(default=7.5, help_text='CFG scale (1.0-20.0)'),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='color_scheme',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutral Elegance'), ('pastels', 'Soft Pastels'), ('jewel_tones', 'Rich Jewel Tones'), ('earth_tones', 'Warm Earth Tones'), ('monochrome', 'Black & White'), ('bold_colors', 'Vibrant Bold Colors'), ('blush_gold', 'Blush & Gold'), ('sage_cream', 'Sage & Cream'), ('navy_copper', 'Navy & Copper'), ('burgundy_ivory', 'Burgundy & Ivory')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='generated_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='lighting_mood',
            field=models.CharField(blank=True, choices=[('romantic', 'Romantic & Intimate'), ('dramatic', 'Dramatic & Bold'), ('soft', 'Soft & Dreamy'), ('vibrant', 'Bright & Energetic'), ('moody', 'Atmospheric & Moody'), ('natural', 'Natural & Fresh')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='output_format',
            field=models.CharField(default='png', max_length=10),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='seed',
            field=models.BigIntegerField(blank=True, help_text='Random seed', null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(choices=[('wedding_ceremony', 'Wedding Ceremony'), ('dance_floor', 'Dance Floor / Party Area'), ('dining_area', 'Reception Dining'), ('cocktail_hour', 'Cocktail Reception'), ('lounge_area', 'Lounge / Seating Area'), ('bridal_suite', 'Bridal Suite / Getting Ready'), ('entrance_area', 'Entrance / Welcome Area'), ('outdoor_patio', 'Outdoor Patio / Terrace'), ('garden_space', 'Garden / Courtyard'), ('ballroom', 'Grand Ballroom')], default='wedding_ceremony', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='special_features',
            field=models.TextField(blank=True, help_text='Special features to highlight or incorporate', null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='steps',
            field=models.IntegerField(default=40, help_text='Generation steps (10-100)'),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='strength',
            field=models.FloatField(default=0.85, help_text='Transformation strength (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='style_intensity',
            field=models.CharField(blank=True, choices=[('subtle', 'Subtle Enhancement'), ('moderate', 'Balanced Transformation'), ('dramatic', 'Bold Transformation'), ('complete', 'Complete Reimagining')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='wedding_theme',
            field=models.CharField(choices=[('rustic', 'Rustic Farmhouse'), ('modern', 'Modern Contemporary'), ('vintage', 'Vintage Romance'), ('bohemian', 'Bohemian Chic'), ('classic', 'Classic Traditional'), ('garden', 'Garden Natural'), ('beach', 'Beach Coastal'), ('industrial', 'Industrial Urban'), ('glamorous', 'Glamorous Luxury'), ('tropical', 'Tropical Paradise'), ('fairy_tale', 'Fairy Tale Enchanted'), ('cultural_fusion', 'Cultural Fusion'), ('japanese_zen', 'Japanese Zen'), ('chinese_dynasty', 'Chinese Dynasty'), ('indian_palace', 'Indian Palace'), ('korean_hanbok', 'Korean Hanbok'), ('thai_temple', 'Thai Temple'), ('scottish_highland', 'Scottish Highland'), ('french_chateau', 'French Château'), ('greek_island', 'Greek Island'), ('italian_villa', 'Italian Villa'), ('english_garden', 'English Garden'), ('mexican_fiesta', 'Mexican Fiesta'), ('spanish_hacienda', 'Spanish Hacienda'), ('brazilian_carnival', 'Brazilian Carnival'), ('argentine_tango', 'Argentine Tango'), ('moroccan_nights', 'Moroccan Nights'), ('arabian_desert', 'Arabian Desert'), ('african_safari', 'African Safari'), ('egyptian_royal', 'Egyptian Royal'), ('winter_wonderland', 'Winter Wonderland'), ('spring_awakening', 'Spring Awakening'), ('summer_solstice', 'Summer Solstice'), ('autumn_harvest', 'Autumn Harvest'), ('forest_enchanted', 'Enchanted Forest'), ('desert_bloom', 'Desert Bloom'), ('ocean_waves', 'Ocean Waves'), ('mountain_vista', 'Mountain Vista'), ('metropolitan_chic', 'Metropolitan Chic'), ('brooklyn_loft', 'Brooklyn Loft'), ('rooftop_garden', 'Rooftop Garden'), ('art_deco_glam', 'Art Deco Glam'), ('scandinavian_simple', 'Scandinavian Simple'), ('modern_monochrome', 'Modern Monochrome'), ('concrete_jungle', 'Concrete Jungle'), ('glass_house', 'Glass House'), ('1950s_diner', '1950s Diner'), ('1960s_mod', '1960s Mod'), ('1970s_disco', '1970s Disco'), ('1980s_neon', '1980s Neon'), ('1990s_grunge', '1990s Grunge'), ('victorian_romance', 'Victorian Romance'), ('art_nouveau', 'Art Nouveau'), ('great_gatsby', 'Great Gatsby')], default='wedding_theme', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GenerationPreset',
        ),
        migrations.DeleteModel(
            name='ProcessingJobEnhanced',
        ),
        migrations.DeleteModel(
            name='PromptTemplate',
        ),
    ]
