# Generated by Django 5.1.8 on 2025-08-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0015_remove_processingjobenhanced_used_preset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(choices=[('wedding_ceremony', 'Wedding Ceremony'), ('dance_floor', 'Dance Floor / Party Area'), ('dining_area', 'Reception Dining'), ('cocktail_hour', 'Cocktail Reception'), ('bridal_suite', 'Bridal Suite / Getting Ready'), ('entrance_area', 'Entrance / Welcome Area')], max_length=20),
        ),
    ]
