# Generated by Django 5.1.8 on 2025-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0016_alter_imageprocessingjob_space_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='avoid',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='cfg_scale',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='negative_prompt',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='output_format',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='special_features',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='style_intensity',
        ),
        migrations.RemoveField(
            model_name='imageprocessingjob',
            name='time_of_day',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='stability_seed',
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='custom_prompt',
            field=models.TextField(blank=True, help_text='Custom prompt for advanced users (overrides theme/style settings)', null=True),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='user_instructions',
            field=models.TextField(blank=True, help_text='Additional instructions added to any prompt (guided or custom)', null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='gemini_model',
            field=models.CharField(default='gemini-2.5-flash-image-preview', max_length=50),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='color_scheme',
            field=models.CharField(blank=True, choices=[('neutral_warm', 'Warm Neutrals (Cream, Beige, Taupe)'), ('neutral_cool', 'Cool Neutrals (Gray, Silver, White)'), ('neutral_natural', 'Natural Neutrals (Linen, Hemp, Stone)'), ('pastels_romantic', 'Romantic Pastels (Blush, Lavender, Sage)'), ('pastels_spring', 'Spring Pastels (Mint, Peach, Baby Blue)'), ('pastels_dusty', 'Dusty Pastels (Mauve, Dusty Rose, Eucalyptus)'), ('jewel_rich', 'Rich Jewels (Emerald, Sapphire, Ruby)'), ('jewel_deep', 'Deep Jewels (Amethyst, Garnet, Topaz)'), ('jewel_ocean', 'Ocean Jewels (Teal, Aquamarine, Pearl)'), ('earth_warm', 'Warm Earth (Terracotta, Rust, Amber)'), ('earth_forest', 'Forest Earth (Moss, Bronze, Mahogany)'), ('earth_desert', 'Desert Earth (Sand, Copper, Sienna)'), ('bold_tropical', 'Tropical Brights (Coral, Turquoise, Lime)'), ('bold_sunset', 'Sunset Colors (Orange, Magenta, Gold)'), ('bold_electric', 'Electric Colors (Fuchsia, Cyan, Yellow)'), ('mono_classic', 'Classic Black & White'), ('mono_silver', 'Silver & Charcoal'), ('mono_gold', 'Gold & Champagne'), ('autumn_harvest', 'Autumn Harvest (Burgundy, Gold, Orange)'), ('winter_frost', 'Winter Frost (Navy, Silver, Ice Blue)'), ('spring_bloom', 'Spring Bloom (Pink, Green, Yellow)'), ('summer_garden', 'Summer Garden (Purple, Coral, Lime)'), ('blush_gold', 'Blush & Gold'), ('sage_cream', 'Sage & Cream'), ('navy_copper', 'Navy & Copper'), ('burgundy_ivory', 'Burgundy & Ivory'), ('mauve_gray', 'Mauve & Gray'), ('dusty_blue_rose', 'Dusty Blue & Rose'), ('forest_gold', 'Forest Green & Gold'), ('plum_silver', 'Plum & Silver')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='lighting_mood',
            field=models.CharField(blank=True, help_text='Lighting atmosphere', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(blank=True, choices=[('wedding_ceremony', 'Wedding Ceremony'), ('dance_floor', 'Dance Floor / Party Area'), ('dining_area', 'Reception Dining'), ('cocktail_hour', 'Cocktail Reception'), ('bridal_suite', 'Bridal Suite / Getting Ready'), ('entrance_area', 'Entrance / Welcome Area')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='wedding_theme',
            field=models.CharField(blank=True, choices=[('rustic', 'Rustic Farmhouse'), ('modern', 'Modern Contemporary'), ('vintage', 'Vintage Romance'), ('bohemian', 'Bohemian Chic'), ('classic', 'Classic Traditional'), ('garden', 'Garden Natural'), ('beach', 'Beach Coastal'), ('industrial', 'Industrial Urban'), ('glamorous', 'Glamorous Luxury'), ('tropical', 'Tropical Paradise'), ('fairy_tale', 'Fairy Tale Enchanted'), ('cultural_fusion', 'Cultural Fusion'), ('japanese_zen', 'Japanese Zen'), ('chinese_dynasty', 'Chinese Dynasty'), ('indian_palace', 'Indian Palace'), ('korean_hanbok', 'Korean Hanbok'), ('thai_temple', 'Thai Temple'), ('scottish_highland', 'Scottish Highland'), ('french_chateau', 'French Château'), ('greek_island', 'Greek Island'), ('italian_villa', 'Italian Villa'), ('english_garden', 'English Garden'), ('mexican_fiesta', 'Mexican Fiesta'), ('spanish_hacienda', 'Spanish Hacienda'), ('brazilian_carnival', 'Brazilian Carnival'), ('argentine_tango', 'Argentine Tango'), ('moroccan_nights', 'Moroccan Nights'), ('arabian_desert', 'Arabian Desert'), ('african_safari', 'African Safari'), ('egyptian_royal', 'Egyptian Royal'), ('winter_wonderland', 'Winter Wonderland'), ('spring_awakening', 'Spring Awakening'), ('summer_solstice', 'Summer Solstice'), ('autumn_harvest', 'Autumn Harvest'), ('forest_enchanted', 'Enchanted Forest'), ('desert_bloom', 'Desert Bloom'), ('ocean_waves', 'Ocean Waves'), ('mountain_vista', 'Mountain Vista'), ('metropolitan_chic', 'Metropolitan Chic'), ('brooklyn_loft', 'Brooklyn Loft'), ('rooftop_garden', 'Rooftop Garden'), ('art_deco_glam', 'Art Deco Glam'), ('scandinavian_simple', 'Scandinavian Simple'), ('modern_monochrome', 'Modern Monochrome'), ('concrete_jungle', 'Concrete Jungle'), ('glass_house', 'Glass House'), ('1950s_diner', '1950s Diner'), ('1960s_mod', '1960s Mod'), ('1970s_disco', '1970s Disco'), ('1980s_neon', '1980s Neon'), ('1990s_grunge', '1990s Grunge'), ('victorian_romance', 'Victorian Romance'), ('art_nouveau', 'Art Nouveau'), ('great_gatsby', 'Great Gatsby')], max_length=50),
        ),
    ]
