# Generated by Django 5.1.8 on 2025-09-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0017_remove_imageprocessingjob_avoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='custom_prompt',
            field=models.TextField(blank=True, help_text='Custom prompt (overrides theme/style settings)', null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='user_instructions',
            field=models.TextField(blank=True, help_text='Additional instructions for any prompt mode', null=True),
        ),
    ]
