# Generated by Django 5.1.8 on 2025-09-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0018_alter_imageprocessingjob_custom_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='color_scheme',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('pink', 'Pink'), ('coral', 'Coral'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('white', 'White'), ('black', 'Black'), ('pastel_pink', 'Pastel Pink'), ('pastel_peach', 'Pastel Peach'), ('pastel_yellow', 'Pastel Yellow'), ('pastel_mint', 'Pastel Mint'), ('pastel_blue', 'Pastel Blue'), ('pastel_lavender', 'Pastel Lavender'), ('pastel_sage', 'Pastel Sage'), ('pastel_cream', 'Pastel Cream'), ('earth_brown', 'Brown & Tan'), ('earth_rust', 'Rust & Terracotta'), ('earth_forest', 'Forest Green & Brown'), ('earth_desert', 'Sand & Copper'), ('earth_autumn', 'Autumn Orange & Brown'), ('earth_moss', 'Moss Green & Stone'), ('black_white', 'Black & White'), ('pink_gold', 'Pink & Gold'), ('blue_white', 'Blue & White'), ('red_white', 'Red & White'), ('sage_cream', 'Sage Green & Cream'), ('blush_gold', 'Blush Pink & Gold'), ('navy_gold', 'Navy Blue & Gold'), ('burgundy_gold', 'Burgundy & Gold'), ('spring_fresh', 'Spring (Pink, Green, Yellow)'), ('summer_bright', 'Summer (Coral, Turquoise, Yellow)'), ('autumn_harvest', 'Autumn (Orange, Burgundy, Gold)'), ('winter_elegant', 'Winter (Navy, Silver, White)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='wedding_theme',
            field=models.CharField(blank=True, choices=[('rustic', 'Rustic Farmhouse'), ('modern', 'Modern Contemporary'), ('vintage', 'Vintage Romance'), ('bohemian', 'Bohemian Chic'), ('classic', 'Classic Traditional'), ('garden', 'Garden Natural'), ('beach', 'Beach Coastal'), ('industrial', 'Industrial Urban'), ('glamorous', 'Glamorous Luxury'), ('tropical', 'Tropical Paradise'), ('fairy_tale', 'Fairy Tale Enchanted'), ('cultural_fusion', 'Cultural Fusion'), ('minimalist', 'Minimalist Clean'), ('romantic', 'Romantic Dreamy'), ('elegant', 'Elegant Sophisticated'), ('chic', 'Chic Contemporary'), ('timeless', 'Timeless Classic'), ('country_barn', 'Country Barn'), ('art_deco', 'Art Deco Glamour'), ('scandinavian', 'Scandinavian Hygge'), ('mediterranean', 'Mediterranean Warmth'), ('prairie_wildflower', 'Prairie Wildflower'), ('winter_wonderland', 'Winter Wonderland'), ('spring_fresh', 'Spring Fresh'), ('harvest_festival', 'Harvest Festival'), ('whimsical', 'Whimsical Playful'), ('monochrome', 'Monochrome Sophisticated'), ('statement_bold', 'Statement Bold'), ('soft_dreamy', 'Soft Dreamy'), ('luxury', 'Luxury Premium'), ('japanese_zen', 'Japanese Zen'), ('chinese_dynasty', 'Chinese Dynasty'), ('indian_palace', 'Indian Palace'), ('korean_hanbok', 'Korean Hanbok'), ('thai_temple', 'Thai Temple'), ('scottish_highland', 'Scottish Highland'), ('french_chateau', 'French Château'), ('greek_island', 'Greek Island'), ('italian_villa', 'Italian Villa'), ('english_garden', 'English Garden'), ('mexican_fiesta', 'Mexican Fiesta'), ('spanish_hacienda', 'Spanish Hacienda'), ('brazilian_carnival', 'Brazilian Carnival'), ('argentine_tango', 'Argentine Tango'), ('moroccan_nights', 'Moroccan Nights'), ('arabian_desert', 'Arabian Desert'), ('african_safari', 'African Safari'), ('egyptian_royal', 'Egyptian Royal'), ('spring_awakening', 'Spring Awakening'), ('summer_solstice', 'Summer Solstice'), ('autumn_harvest', 'Autumn Harvest'), ('forest_enchanted', 'Enchanted Forest'), ('desert_bloom', 'Desert Bloom'), ('ocean_waves', 'Ocean Waves'), ('mountain_vista', 'Mountain Vista'), ('metropolitan_chic', 'Metropolitan Chic'), ('brooklyn_loft', 'Brooklyn Loft'), ('rooftop_garden', 'Rooftop Garden'), ('art_deco_glam', 'Art Deco Glam'), ('scandinavian_simple', 'Scandinavian Simple'), ('modern_monochrome', 'Modern Monochrome'), ('concrete_jungle', 'Concrete Jungle'), ('glass_house', 'Glass House'), ('1950s_diner', '1950s Diner'), ('1960s_mod', '1960s Mod'), ('1970s_disco', '1970s Disco'), ('1980s_neon', '1980s Neon'), ('1990s_grunge', '1990s Grunge'), ('victorian_romance', 'Victorian Romance'), ('art_nouveau', 'Art Nouveau'), ('great_gatsby', 'Great Gatsby')], max_length=50),
        ),
    ]
