# Generated by Django 5.1.8 on 2025-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0019_alter_imageprocessingjob_color_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='lighting_mood',
            field=models.CharField(blank=True, choices=[('romantic', 'Romantic Candlelit'), ('bright', 'Bright & Cheerful'), ('dim', 'Intimate & Cozy'), ('dramatic', 'Dramatic & Bold'), ('natural', 'Natural Daylight'), ('golden', 'Golden Hour'), ('dusk', 'Twilight Dusk'), ('dawn', 'Dawn Morning Light')], help_text='Lighting atmosphere', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall/Autumn'), ('winter', 'Winter')], help_text='Wedding season', max_length=20),
        ),
    ]
