# Generated by Django 5.1.8 on 2025-09-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0020_alter_imageprocessingjob_lighting_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='user_instructions',
            field=models.TextField(blank=True, help_text='Additional instructions for the transformation', null=True),
        ),
    ]
