# Generated by Django 5.1.8 on 2025-10-22 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0023_alter_imageprocessingjob_wedding_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingjob',
            name='attire_style',
            field=models.CharField(blank=True, choices=[('traditional_formal', 'Traditional Wedding Attire'), ('modern_chic', 'Modern Chic'), ('casual_elegant', 'Casual Elegant'), ('bohemian', 'Bohemian Style'), ('vintage_inspired', 'Vintage Inspired'), ('cultural_traditional', 'Cultural Traditional')], max_length=30),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='photo_theme',
            field=models.CharField(blank=True, choices=[('classic_elegant', 'Classic Elegant'), ('modern_romantic', 'Modern Romantic'), ('outdoor_natural', 'Outdoor Natural'), ('vintage_timeless', 'Vintage Timeless'), ('destination_exotic', 'Destination Exotic'), ('bohemian_free', 'Bohemian Free-Spirited'), ('luxury_glamour', 'Luxury Glamour'), ('casual_lifestyle', 'Casual Lifestyle')], max_length=50),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='pose_style',
            field=models.CharField(blank=True, choices=[('formal_portrait', 'Formal Portrait'), ('romantic_embrace', 'Romantic Embrace'), ('candid_laughing', 'Candid & Laughing'), ('walking_together', 'Walking Together'), ('sitting_intimate', 'Sitting Intimate'), ('dancing', 'Dancing'), ('playful_fun', 'Playful & Fun')], max_length=30),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='setting_type',
            field=models.CharField(blank=True, choices=[('studio', 'Studio / Indoor'), ('garden', 'Garden / Park'), ('beach', 'Beach / Waterfront'), ('urban', 'Urban / City'), ('countryside', 'Countryside / Rural'), ('venue_interior', 'Wedding Venue Interior'), ('mountain', 'Mountain / Vista'), ('forest', 'Forest / Woods')], max_length=30),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='studio_mode',
            field=models.CharField(choices=[('venue', 'Venue Design'), ('portrait_wedding', 'Wedding Portrait'), ('portrait_engagement', 'Engagement Portrait')], default='venue', max_length=20),
        ),
        migrations.AddField(
            model_name='userimage',
            name='image_type',
            field=models.CharField(choices=[('venue', 'Venue Photo'), ('face', 'Face Photo'), ('reference', 'Reference Image')], default='venue', help_text='Type of image uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='color_scheme',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('pink', 'Pink'), ('coral', 'Coral'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('white', 'White'), ('black', 'Black'), ('pastel_pink', 'Pastel Pink'), ('pastel_peach', 'Pastel Peach'), ('pastel_mint', 'Pastel Mint'), ('pastel_blue', 'Pastel Blue'), ('pastel_lavender', 'Pastel Lavender')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='custom_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='lighting_mood',
            field=models.CharField(blank=True, choices=[('romantic', 'Romantic Candlelit'), ('bright', 'Bright & Cheerful'), ('dim', 'Intimate & Cozy'), ('dramatic', 'Dramatic & Bold'), ('natural', 'Natural Daylight'), ('golden', 'Golden Hour'), ('dusk', 'Twilight Dusk'), ('dawn', 'Dawn Morning Light')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall/Autumn'), ('winter', 'Winter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='user_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='wedding_theme',
            field=models.CharField(blank=True, choices=[('rustic', 'Rustic Farmhouse'), ('modern', 'Modern Contemporary'), ('vintage', 'Vintage Romance'), ('classic', 'Classic Traditional'), ('garden', 'Garden Natural'), ('beach', 'Beach Coastal'), ('industrial', 'Industrial Urban'), ('bohemian', 'Bohemian Chic'), ('glamorous', 'Glamorous Luxury'), ('tropical', 'Tropical Paradise'), ('fairy_tale', 'Fairy Tale Enchanted'), ('minimalist', 'Minimalist Clean'), ('romantic', 'Romantic Dreamy'), ('elegant', 'Elegant Sophisticated'), ('chic', 'Chic Contemporary'), ('timeless', 'Timeless Classic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='venue_description',
            field=models.TextField(blank=True, help_text='Description or notes'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='venue_name',
            field=models.CharField(blank=True, help_text='Name or label', max_length=200),
        ),
        migrations.CreateModel(
            name='FavoriteUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_used', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='image_processing.userimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Upload',
                'verbose_name_plural': 'Favorite Uploads',
                'ordering': ['-last_used', '-created_at'],
                'unique_together': {('user', 'image')},
            },
        ),
        migrations.CreateModel(
            name='JobReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order of reference images')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='image_processing.imageprocessingjob')),
                ('reference_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_processing.userimage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('job', 'reference_image')},
            },
        ),
    ]
