# Generated by Django 5.1.8 on 2025-10-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0024_imageprocessingjob_attire_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='attire_style',
            field=models.CharField(blank=True, choices=[('traditional_formal', 'Traditional Wedding Attire'), ('modern_chic', 'Modern Chic'), ('casual_elegant', 'Casual Elegant'), ('bohemian', 'Bohemian Style'), ('vintage_inspired', 'Vintage Inspired'), ('cultural_traditional', 'Cultural Traditional'), ('formal_elegant', 'Formal Elegant'), ('cozy_casual', 'Cozy Casual'), ('activity_specific', 'Activity-Specific'), ('use_pictured', 'Use Pictured Attire')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='color_scheme',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('pink', 'Pink'), ('coral', 'Coral'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('white', 'White'), ('black', 'Black'), ('pastel_pink', 'Pastel Pink'), ('pastel_peach', 'Pastel Peach'), ('pastel_yellow', 'Pastel Yellow'), ('pastel_mint', 'Pastel Mint'), ('pastel_blue', 'Pastel Blue'), ('pastel_lavender', 'Pastel Lavender'), ('pastel_sage', 'Pastel Sage'), ('pastel_cream', 'Pastel Cream'), ('earth_brown', 'Earth Brown'), ('earth_rust', 'Earth Rust'), ('earth_forest', 'Earth Forest'), ('earth_desert', 'Earth Desert'), ('earth_autumn', 'Earth Autumn'), ('earth_moss', 'Earth Moss'), ('black_white', 'Black & White'), ('pink_gold', 'Pink & Gold'), ('blue_white', 'Blue & White'), ('red_white', 'Red & White'), ('sage_cream', 'Sage & Cream'), ('blush_gold', 'Blush & Gold'), ('navy_gold', 'Navy & Gold'), ('burgundy_gold', 'Burgundy & Gold'), ('spring_fresh', 'Spring Fresh'), ('summer_bright', 'Summer Bright'), ('autumn_harvest', 'Autumn Harvest'), ('winter_elegant', 'Winter Elegant'), ('vibrant_bold', 'Vibrant Bold'), ('light_airy_pastels', 'Light Airy Pastels'), ('earth_tones_natural', 'Earth Tones Natural'), ('moody_dramatic', 'Moody Dramatic'), ('black_white_classic', 'Black & White Classic'), ('warm_tones', 'Warm Tones'), ('cool_tones', 'Cool Tones'), ('use_pictured', 'Use Pictured Colors')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='lighting_mood',
            field=models.CharField(blank=True, choices=[('dawn', 'Dawn Morning Light'), ('morning', 'Morning Light'), ('midday', 'Midday Bright'), ('golden', 'Golden Hour'), ('dusk', 'Twilight Dusk'), ('evening', 'Evening'), ('night', 'Night'), ('romantic', 'Romantic Warm'), ('bright', 'Bright & Cheerful'), ('dim', 'Intimate & Cozy'), ('dramatic', 'Dramatic & Bold'), ('candlelit', 'Candlelit'), ('natural', 'Natural Daylight'), ('fluorescent', 'Fluorescent Bright'), ('rainy', 'Rainy/Overcast'), ('use_pictured', 'Use Pictured Lighting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='photo_theme',
            field=models.CharField(blank=True, choices=[('classic_elegant', 'Classic Elegant'), ('modern_romantic', 'Modern Romantic'), ('outdoor_natural', 'Outdoor Natural'), ('vintage_timeless', 'Vintage Timeless'), ('destination_exotic', 'Destination Exotic'), ('bohemian_free', 'Bohemian Free-Spirited'), ('luxury_glamour', 'Luxury Glamour'), ('casual_lifestyle', 'Casual Lifestyle'), ('urban_chic', 'Urban Chic'), ('minimalist_modern', 'Minimalist Modern'), ('use_pictured', 'Use Pictured Style')], max_length=50),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='pose_style',
            field=models.CharField(blank=True, choices=[('formal_portrait', 'Formal Portrait'), ('romantic_embrace', 'Romantic Embrace'), ('candid_laughing', 'Candid & Laughing'), ('walking_together', 'Walking Together'), ('sitting_intimate', 'Sitting Intimate'), ('dancing', 'Dancing'), ('playful_fun', 'Playful & Fun'), ('forehead_kiss', 'Forehead Kiss'), ('looking_at_each_other', 'Looking at Each Other'), ('playing_board_game', 'Playing Board Game'), ('cooking_together', 'Cooking Together'), ('hiking', 'Hiking'), ('coffee_date', 'Coffee Date'), ('skiing_snowboarding', 'Skiing/Snowboarding'), ('reading_together', 'Reading Together'), ('picnic', 'Picnic'), ('biking', 'Biking'), ('use_pictured', 'Use Pictured Pose/Activity')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall/Autumn'), ('winter', 'Winter'), ('use_pictured', 'Use Pictured Season')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='setting_type',
            field=models.CharField(blank=True, choices=[('studio', 'Studio / Indoor'), ('garden', 'Garden / Park'), ('beach', 'Beach / Waterfront'), ('urban', 'Urban / City'), ('countryside', 'Countryside / Rural'), ('venue_interior', 'Wedding Venue Interior'), ('mountain', 'Mountain / Vista'), ('forest', 'Forest / Woods'), ('home', 'Home / Cozy Indoor'), ('coffee_shop', 'Coffee Shop / Café'), ('use_pictured', 'Use Pictured Location')], max_length=30),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='space_type',
            field=models.CharField(blank=True, choices=[('wedding_ceremony', 'Wedding Ceremony'), ('dance_floor', 'Dance Floor / Party Area'), ('dining_area', 'Reception Dining'), ('cocktail_hour', 'Cocktail Reception'), ('bridal_suite', 'Bridal Suite / Getting Ready'), ('entrance_area', 'Entrance / Welcome Area'), ('use_pictured', 'Use Pictured Space')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingjob',
            name='wedding_theme',
            field=models.CharField(blank=True, choices=[('rustic', 'Rustic Farmhouse'), ('modern', 'Modern Contemporary'), ('vintage', 'Vintage Romance'), ('classic', 'Classic Traditional'), ('garden', 'Garden Natural'), ('beach', 'Beach Coastal'), ('industrial', 'Industrial Urban'), ('bohemian', 'Bohemian Chic'), ('glamorous', 'Glamorous Luxury'), ('tropical', 'Tropical Paradise'), ('fairy_tale', 'Fairy Tale Enchanted'), ('minimalist', 'Minimalist Clean'), ('romantic', 'Romantic Dreamy'), ('elegant', 'Elegant Sophisticated'), ('chic', 'Chic Contemporary'), ('timeless', 'Timeless Classic'), ('country_barn', 'Country Barn'), ('art_deco', 'Art Deco Glamour'), ('scandinavian', 'Scandinavian Hygge'), ('mediterranean', 'Mediterranean'), ('prairie_wildflower', 'Prairie Wildflower'), ('winter_wonderland', 'Winter Wonderland'), ('spring_fresh', 'Spring Fresh'), ('harvest_festival', 'Harvest Festival'), ('whimsical', 'Whimsical Playful'), ('monochrome', 'Monochrome B&W'), ('statement_bold', 'Bold Statement'), ('soft_dreamy', 'Soft Dreamy'), ('luxury', 'Premium Luxury'), ('japanese_zen', 'Japanese Zen'), ('chinese_dynasty', 'Chinese Dynasty'), ('indian_palace', 'Indian Palace'), ('korean_hanbok', 'Korean Hanbok'), ('thai_temple', 'Thai Temple'), ('scottish_highland', 'Scottish Highland'), ('french_chateau', 'French Château'), ('greek_island', 'Greek Island'), ('italian_villa', 'Italian Villa'), ('english_garden', 'English Garden'), ('mexican_fiesta', 'Mexican Fiesta'), ('spanish_hacienda', 'Spanish Hacienda'), ('brazilian_carnival', 'Brazilian Carnival'), ('argentine_tango', 'Argentine Tango'), ('moroccan_nights', 'Moroccan Nights'), ('arabian_desert', 'Arabian Desert'), ('african_safari', 'African Safari'), ('egyptian_royal', 'Egyptian Royal'), ('spring_awakening', 'Spring Awakening'), ('summer_solstice', 'Summer Solstice'), ('autumn_harvest', 'Autumn Harvest'), ('forest_enchanted', 'Enchanted Forest'), ('desert_bloom', 'Desert Bloom'), ('ocean_waves', 'Ocean Waves'), ('mountain_vista', 'Mountain Vista'), ('metropolitan_chic', 'Metropolitan Chic'), ('brooklyn_loft', 'Brooklyn Loft'), ('rooftop_garden', 'Rooftop Garden'), ('art_deco_glam', 'Art Deco Glam'), ('concrete_jungle', 'Concrete Jungle'), ('glass_house', 'Glass House'), ('1950s_diner', '1950s Diner Retro'), ('1960s_mod', '1960s Mod'), ('1970s_disco', '1970s Disco'), ('1980s_neon', '1980s Neon'), ('1990s_grunge', '1990s Grunge'), ('victorian_romance', 'Victorian Romance'), ('art_nouveau', 'Art Nouveau'), ('great_gatsby', 'Great Gatsby'), ('use_pictured', 'Use Pictured Style')], max_length=50),
        ),
    ]
