# Generated by Django 5.1.8 on 2025-10-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0025_alter_imageprocessingjob_attire_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreferenceimage',
            name='reference_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_processing.userimage'),
        ),
    ]
