# Generated by Django 5.1.8 on 2025-09-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_blogpost_blogcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image_webp',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Main content with rich text editor (Summernote)'),
        ),
    ]
