# Generated by Django 5.1.8 on 2025-05-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['product__display_order', 'interval', 'amount']},
        ),
        migrations.AddField(
            model_name='price',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional name to display instead of the default', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this pricing option on the pricing page'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order to display products (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text="Feature list in JSON format. Example: ['Feature 1', 'Feature 2']", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Highlight this product on the pricing page'),
        ),
        migrations.AddField(
            model_name='product',
            name='tokens',
            field=models.IntegerField(default=0, help_text='Number of tokens/actions included with this product'),
        ),
    ]
