# Generated by Django 5.1.8 on 2025-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_price_options_price_display_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_site',
            field=models.BooleanField(default=True, help_text='Show this product on the pricing page'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tokens',
            field=models.IntegerField(default=5, help_text='Number of tokens/actions included with this product'),
        ),
    ]
