# Generated by Django 5.1.8 on 2025-07-08 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_processing', '0004_alter_favorite_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Wedding Shopping List', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared with Link'), ('public', 'Public Registry')], default='private', max_length=10)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('bride_name', models.CharField(blank=True, max_length=100)),
                ('groom_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='image_processing.processedimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ceremony', 'Ceremony'), ('reception', 'Reception'), ('lighting', 'Lighting'), ('furniture', 'Furniture'), ('textiles', 'Textiles & Linens'), ('tableware', 'Tableware'), ('flowers', 'Flowers & Decor'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Must Have'), (2, 'Important'), (3, 'Nice to Have')], default=2)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_purchased', models.BooleanField(default=False)),
                ('purchased_by', models.CharField(blank=True, max_length=100)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('selection_x', models.IntegerField(help_text='X coordinate of selection rectangle')),
                ('selection_y', models.IntegerField(help_text='Y coordinate of selection rectangle')),
                ('selection_width', models.IntegerField(help_text='Width of selection rectangle')),
                ('selection_height', models.IntegerField(help_text='Height of selection rectangle')),
                ('cropped_image', models.ImageField(blank=True, null=True, upload_to='shopping/crops/')),
                ('ai_description', models.TextField(blank=True, help_text='AI-generated item description')),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI confidence score 0-1')),
                ('ai_tags', models.JSONField(default=list, help_text='AI-generated tags')),
                ('product_url', models.URLField(blank=True, null=True)),
                ('affiliate_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('retailer', models.CharField(choices=[('amazon', 'Amazon'), ('wayfair', 'Wayfair'), ('target', 'Target'), ('ikea', 'IKEA'), ('pottery_barn', 'Pottery Barn'), ('williams_sonoma', 'Williams Sonoma'), ('crate_barrel', 'Crate & Barrel'), ('etsy', 'Etsy'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wedding_shopping.shoppinglist')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_selected', models.IntegerField(default=0)),
                ('items_purchased', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wedding_shopping.shoppinglist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
