# Generated by Django 5.1.8 on 2025-07-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrylink',
            name='registry_type',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('target', 'Target'), ('bed_bath_beyond', 'Bed Bath & Beyond'), ('williams_sonoma', 'Williams Sonoma'), ('crate_barrel', 'Crate & Barrel'), ('pottery_barn', 'Pottery Barn'), ('macy', "Macy's"), ('zola', 'Zola'), ('the_knot', 'The Knot'), ('wayfair', 'Wayfair'), ('registry_finder', 'Registry Finder'), ('honeyfund', 'Honeyfund'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('website', 'Website'), ('other', 'Other')], max_length=20),
        ),
    ]
