# Generated by Django 5.1.8 on 2025-07-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0002_alter_registrylink_registry_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeddingPhotoCollection',
        ),
    ]
