# Generated by Django 5.1.8 on 2025-07-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0003_delete_weddingphotocollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20),
        ),
    ]
