# Generated by Django 5.1.8 on 2025-07-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0005_rename_url_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrylink',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='registrylink',
            name='affiliate_url',
        ),
        migrations.RemoveField(
            model_name='registrylink',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='registrylink',
            name='registry_type',
        ),
        migrations.AlterUniqueTogether(
            name='socialmedialink',
            unique_together={('couple_profile', 'url')},
        ),
        migrations.AlterField(
            model_name='registrylink',
            name='registry_name',
            field=models.CharField(help_text="Registry name (e.g., 'Our Home Registry')", max_length=100),
        ),
        migrations.AlterField(
            model_name='registrylink',
            name='url',
            field=models.URLField(help_text='Registry URL'),
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='platform_name',
        ),
    ]
