# Generated by Django 5.1.8 on 2025-08-01 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0006_alter_registrylink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['owner', 'id']},
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='owner',
            field=models.CharField(choices=[('partner_1', 'Partner 1'), ('partner_2', 'Partner 2'), ('shared', 'Both/Shared')], default='shared', max_length=20),
        ),
        migrations.CreateModel(
            name='WeddingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('registry', 'Wedding Registry'), ('rsvp', 'RSVP Site'), ('livestream', 'Live Stream'), ('photos', 'Wedding Photos'), ('website', 'Wedding Website'), ('other', 'Other')], default='registry', max_length=20)),
                ('url', models.URLField(help_text='Link URL')),
                ('title', models.CharField(help_text='Title for this link', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this link')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_links', to='wedding_shopping.coupleprofile')),
            ],
            options={
                'ordering': ['link_type', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RegistryLink',
        ),
    ]
