# Generated by Django 5.1.8 on 2025-08-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0007_alter_socialmedialink_options_socialmedialink_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='weddinglink',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='owner',
        ),
    ]
