# Generated by Django 5.1.8 on 2025-08-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0008_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupleprofile',
            name='engagement_photo',
            field=models.ImageField(blank=True, help_text='Engagement or additional couple photo', null=True, upload_to='engagement_photos/'),
        ),
    ]
