# Generated by Django 5.1.8 on 2025-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0009_coupleprofile_engagement_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weddinglink',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='coupleprofile',
            name='engagement_photo',
        ),
        migrations.RemoveField(
            model_name='weddinglink',
            name='link_type',
        ),
        migrations.AlterField(
            model_name='coupleprofile',
            name='couple_photo',
            field=models.ImageField(blank=True, help_text='Main photo of the couple', null=True, upload_to='couple_photos/'),
        ),
        migrations.AlterField(
            model_name='coupleprofile',
            name='venue_photo',
            field=models.ImageField(blank=True, help_text='Venue photo or additional couple photo', null=True, upload_to='venue_photos/'),
        ),
        migrations.AlterField(
            model_name='weddinglink',
            name='title',
            field=models.CharField(help_text='Site or link title', max_length=100),
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
