# Generated by Django 5.1.8 on 2025-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0010_alter_weddinglink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupleprofile',
            name='venue_location',
            field=models.CharField(blank=True, help_text='Full address or City, State', max_length=200),
        ),
    ]
