# Generated by Django 5.1.8 on 2025-10-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_shopping', '0011_alter_coupleprofile_venue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupleprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Make this profile publicly accessible'),
        ),
    ]
